project_id = "hruykkurtskodirgijgv"

[functions.process-image]
verify_jwt = false

[functions.process-text]
verify_jwt = false

[functions.text-to-speech]
verify_jwt = false

[functions.translate-text]
verify_jwt = false
